server {
    listen 80;
    server_name _;
    root /usr/share/nginx/html;
    index index.html;

    location / {
        try_files $uri $uri/ $uri.html =404;
    }

    location = /docs {
        return 301 /docs/;
    }

    location /docs/ {
        rewrite ^/docs/(.*)$ /$1 break;
        try_files $uri $uri/ $uri.html =404;
    }

    location ~ /\. {
        deny all;
        return 404;
    }
}
